# Generated by Django 4.1 on 2022-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(default='none', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(default='desc', max_length=20)),
                ('product_date', models.DateField()),
            ],
        ),
    ]
